pipeline:

  install:
    image: node:10.15.1
    commands:
      - apt-get update
      - apt-get install -y bluetooth bluez libbluetooth-dev libudev-dev
      - npm install

  build:
    image: node:10.15.1
    commands:
      - npm run all

  publish:
    image: plugins/npm
    username: nathankellenicki
    token:
      from_secret: NPM_TOKEN
    when:
      ref:
        - refs/tags/v*